// =============================================================================
// ENGINE PUBLIC API
// Everything the UI (or tests) needs, exported from one place.
// =============================================================================

// Core types
export type {
  GameState,
  GameAction,
  ActionResult,
  GameEvent,
  CardDefinition,
  CardInstance,
  CardVariant,
  CardVariantType,
  PlayerID,
  ZoneName,
  InkColor,
  CardType,
  Keyword,
  Ability,
  Effect,
  PlayerState,
  GamePhase,
  PendingChoice,
  GameLogEntry,
  RngState,
} from "./types/index.js";

// Engine functions
export { applyAction, getAllLegalActions, checkWinConditions, getLoreThreshold } from "./engine/reducer.js";
export type { WinResult } from "./engine/reducer.js";
export { createGame, parseDecklist, serializeDecklist } from "./engine/initializer.js";
export type { GameConfig, DeckEntry } from "./engine/initializer.js";

// Utilities
export {
  getInstance,
  getDefinition,
  getZone,
  getZoneInstances,
  getEffectiveStrength,
  getEffectiveWillpower,
  getEffectiveLore,
  hasKeyword,
  getKeywordValue,
  getOpponent,
  canAfford,
  isMainPhase,
  matchesFilter,
  findMatchingInstances,
  generateId,
  isSong,
  canSingSong,
  evaluateCondition,
} from "./utils/index.js";

// Game modifiers (static-effect state computed per frame)
export { getGameModifiers } from "./engine/gameModifiers.js";
export type { GameModifiers } from "./engine/gameModifiers.js";

// Seeded RNG
export { createRng, cloneRng, rngNext, rngNextInt } from "./utils/seededRng.js";

// Card definitions (generated by scripts/import-cards-rav.ts)
export { CARD_DEFINITIONS, ALL_CARDS } from "./cards/cardDefinitions.js";

// Engine version stamp (for historical replay compatibility tracking)
export { ENGINE_VERSION } from "./version.js";

// Format legality (Core vs. Infinity — multi-rotation registry)
export {
  CORE_ROTATIONS,
  INFINITY_ROTATIONS,
  isCardLegalInFormat,
  isLegalFor,
  listOfferedRotations,
} from "./formats/legality.js";
export type {
  GameFormat,
  GameFormatFamily,
  RotationId,
  RotationEntry,
  LegalityIssue,
  LegalityResult,
} from "./formats/legality.js";
