// =============================================================================
// CARD DEFINITIONS — loads per-set JSON files and merges them.
// Card data is auto-generated by scripts/import-cards-rav.ts  or
// scripts/import-cards-rav.ts (Ravensburger). Abilities are manually
// implemented. Add new sets by re-running the import script.
// =============================================================================

import type { CardDefinition } from "../types/index.js";
import { buildCardDefinitions } from "./buildDefinitions.js";
import set001 from "./card-set-001.json" assert { type: "json" };
import set002 from "./card-set-002.json" assert { type: "json" };
import set003 from "./card-set-003.json" assert { type: "json" };
import set004 from "./card-set-004.json" assert { type: "json" };
import set005 from "./card-set-005.json" assert { type: "json" };
import set006 from "./card-set-006.json" assert { type: "json" };
import set007 from "./card-set-007.json" assert { type: "json" };
import set008 from "./card-set-008.json" assert { type: "json" };
import set009 from "./card-set-009.json" assert { type: "json" };
import set010 from "./card-set-010.json" assert { type: "json" };
import set011 from "./card-set-011.json" assert { type: "json" };
import set012 from "./card-set-012.json" assert { type: "json" };
import set0C1 from "./card-set-0C1.json" assert { type: "json" };
import set0C2 from "./card-set-0C2.json" assert { type: "json" };
import set0P1 from "./card-set-0P1.json" assert { type: "json" };
import set0P2 from "./card-set-0P2.json" assert { type: "json" };
import set0P3 from "./card-set-0P3.json" assert { type: "json" };
import setD23 from "./card-set-D23.json" assert { type: "json" };

type RawCard = CardDefinition & { _namedAbilityStubs?: string[] };

function loadSet(raw: unknown[]): CardDefinition[] {
  return (raw as RawCard[])
    .map(({ _namedAbilityStubs: _, ...card }) => card as unknown as CardDefinition);
}

const cards = [
  ...loadSet(set001),
  ...loadSet(set002),
  ...loadSet(set003),
  ...loadSet(set004),
  ...loadSet(set005),
  ...loadSet(set006),
  ...loadSet(set007),
  ...loadSet(set008),
  ...loadSet(set009),
  ...loadSet(set010),
  ...loadSet(set011),
  ...loadSet(set012),
  ...loadSet(set0C1),
  ...loadSet(set0C2),
  ...loadSet(set0P1),
  ...loadSet(set0P2),
  ...loadSet(set0P3),
  ...loadSet(setD23),
];

const built = buildCardDefinitions(cards);

/** Canonical definition per slug. Duplicates across sets (reprints, enchanted
 *  alt-arts, promos) collapse into one entry with `variants[]` listing the
 *  distinct visual printings. */
export const CARD_DEFINITIONS: Record<string, CardDefinition> = built.byId;

export const ALL_CARDS: CardDefinition[] = built.all;
