// =============================================================================
// CARD DEFINITIONS — loads per-set JSON files and merges them.
// Card data is auto-generated by scripts/import-cards-rav.ts  or
// scripts/import-cards-rav.ts (Ravensburger). Abilities are manually
// implemented. Add new sets by re-running the import script.
// =============================================================================

import type { CardDefinition } from "../types/index.js";
import { buildCardDefinitions } from "./buildDefinitions.js";
import set1 from "./card-set-1.json" assert { type: "json" };
import set2 from "./card-set-2.json" assert { type: "json" };
import set3 from "./card-set-3.json" assert { type: "json" };
import set4 from "./card-set-4.json" assert { type: "json" };
import set5 from "./card-set-5.json" assert { type: "json" };
import set6 from "./card-set-6.json" assert { type: "json" };
import set7 from "./card-set-7.json" assert { type: "json" };
import set8 from "./card-set-8.json" assert { type: "json" };
import set9 from "./card-set-9.json" assert { type: "json" };
import set10 from "./card-set-10.json" assert { type: "json" };
import set11 from "./card-set-11.json" assert { type: "json" };
import set12 from "./card-set-12.json" assert { type: "json" };
import setC1 from "./card-set-C1.json" assert { type: "json" };
import setC2 from "./card-set-C2.json" assert { type: "json" };
import setD23 from "./card-set-D23.json" assert { type: "json" };
import setDIS from "./card-set-DIS.json" assert { type: "json" };
import setP1 from "./card-set-P1.json" assert { type: "json" };
import setP2 from "./card-set-P2.json" assert { type: "json" };
import setP3 from "./card-set-P3.json" assert { type: "json" };

type RawCard = CardDefinition & { _namedAbilityStubs?: string[] };

function loadSet(raw: unknown[]): CardDefinition[] {
  return (raw as RawCard[])
    .map(({ _namedAbilityStubs: _, ...card }) => card as unknown as CardDefinition);
}

const cards = [
  ...loadSet(set1),
  ...loadSet(set2),
  ...loadSet(set3),
  ...loadSet(set4),
  ...loadSet(set5),
  ...loadSet(set6),
  ...loadSet(set7),
  ...loadSet(set8),
  ...loadSet(set9),
  ...loadSet(set10),
  ...loadSet(set11),
  ...loadSet(set12),
  ...loadSet(setC1),
  ...loadSet(setC2),
  ...loadSet(setD23),
  ...loadSet(setDIS),
  ...loadSet(setP1),
  ...loadSet(setP2),
  ...loadSet(setP3),
];

const built = buildCardDefinitions(cards);

/** Canonical definition per slug. Duplicates across sets (reprints, enchanted
 *  alt-arts, promos) collapse into one entry with `variants[]` listing the
 *  distinct visual printings. */
export const CARD_DEFINITIONS: Record<string, CardDefinition> = built.byId;

export const ALL_CARDS: CardDefinition[] = built.all;
