// =============================================================================
// LORCAST CARD DEFINITIONS — auto-generated by scripts/import-cards.ts
// DO NOT EDIT MANUALLY — re-run the script to regenerate.
//
// Cards with named abilities have abilities: [] (vanilla stubs).
// Search for _namedAbilityStubs in lorcast-cards.json to find cards
// that need manual ability implementation.
// =============================================================================

import type { CardDefinition } from "../types/index.js";
import rawCards from "./lorcast-cards.json" assert { type: "json" };

// Strip the _namedAbilityStubs field before exporting (it's not on CardDefinition).
// `as unknown as` is intentional — TypeScript's JSON inference includes `undefined`
// in optional property types, which conflicts with exactOptionalPropertyTypes.
// The JSON data is correct at runtime; this cast is safe.
type RawCard = CardDefinition & { _namedAbilityStubs?: string[] };
const cards = (rawCards as unknown as RawCard[])
  .map(({ _namedAbilityStubs: _, ...card }) => card as unknown as CardDefinition);

export const LORCAST_CARD_DEFINITIONS: Record<string, CardDefinition> =
  Object.fromEntries(cards.map((c) => [c.id, c]));

export const LORCAST_CARDS: CardDefinition[] = cards;
