// =============================================================================
// LORCAST CARD DEFINITIONS — loads per-set JSON files and merges them.
// Card data is auto-generated by scripts/import-cards.ts (Lorcast) or
// scripts/import-cards-rav.ts (Ravensburger). Abilities are manually
// implemented. Add new sets by re-running the import script.
// =============================================================================

import type { CardDefinition } from "../types/index.js";
import set001 from "./lorcast-set-001.json" assert { type: "json" };
import set002 from "./lorcast-set-002.json" assert { type: "json" };
import set003 from "./lorcast-set-003.json" assert { type: "json" };
import set004 from "./lorcast-set-004.json" assert { type: "json" };
import set005 from "./lorcast-set-005.json" assert { type: "json" };
import set006 from "./lorcast-set-006.json" assert { type: "json" };
import set007 from "./lorcast-set-007.json" assert { type: "json" };
import set008 from "./lorcast-set-008.json" assert { type: "json" };
import set009 from "./lorcast-set-009.json" assert { type: "json" };
import set010 from "./lorcast-set-010.json" assert { type: "json" };
import set011 from "./lorcast-set-011.json" assert { type: "json" };
import set012 from "./lorcast-set-012.json" assert { type: "json" };
import set0P1 from "./lorcast-set-0P1.json" assert { type: "json" };
import set0P2 from "./lorcast-set-0P2.json" assert { type: "json" };
import set0P3 from "./lorcast-set-0P3.json" assert { type: "json" };
import set0cp from "./lorcast-set-0cp.json" assert { type: "json" };
import setD23 from "./lorcast-set-D23.json" assert { type: "json" };
import setDIS from "./lorcast-set-DIS.json" assert { type: "json" };

type RawCard = CardDefinition & { _namedAbilityStubs?: string[] };

function loadSet(raw: unknown[]): CardDefinition[] {
  return (raw as RawCard[])
    .map(({ _namedAbilityStubs: _, ...card }) => card as unknown as CardDefinition);
}

const cards = [
  ...loadSet(set001),
  ...loadSet(set002),
  ...loadSet(set003),
  ...loadSet(set004),
  ...loadSet(set005),
  ...loadSet(set006),
  ...loadSet(set007),
  ...loadSet(set008),
  ...loadSet(set009),
  ...loadSet(set010),
  ...loadSet(set011),
  ...loadSet(set012),
  ...loadSet(set0P1),
  ...loadSet(set0P2),
  ...loadSet(set0P3),
  ...loadSet(set0cp),
  ...loadSet(setD23),
  ...loadSet(setDIS),
];

/** Count manually-implemented abilities (non-keyword) + actionEffects on a card. */
function manualAbilityCount(c: CardDefinition): number {
  const nonKeyword = c.abilities.filter(a => a.type !== "keyword").length;
  const actionFx = c.actionEffects?.length ?? 0;
  return nonKeyword + actionFx;
}

/** For duplicate IDs (reprints), keep the copy with more implemented abilities. */
export const LORCAST_CARD_DEFINITIONS: Record<string, CardDefinition> =
  cards.reduce<Record<string, CardDefinition>>((map, c) => {
    const existing = map[c.id];
    if (!existing || manualAbilityCount(c) > manualAbilityCount(existing)) {
      map[c.id] = c;
    }
    return map;
  }, {});

export const LORCAST_CARDS: CardDefinition[] = cards;
