// =============================================================================
// LORCAST CARD DEFINITIONS — loads per-set JSON files and merges them.
// Card data is auto-generated by scripts/import-cards.ts, then abilities
// are manually implemented. Add new sets as lorcast-set-XXX.json imports.
// =============================================================================

import type { CardDefinition } from "../types/index.js";
import set001 from "./lorcast-set-001.json" assert { type: "json" };

// Add future sets here:
// import set002 from "./lorcast-set-002.json" assert { type: "json" };

// Strip _namedAbilityStubs (import-time metadata, not part of CardDefinition).
// `as unknown as` is intentional — TypeScript's JSON inference includes `undefined`
// in optional property types, which conflicts with exactOptionalPropertyTypes.
type RawCard = CardDefinition & { _namedAbilityStubs?: string[] };

function loadSet(raw: unknown[]): CardDefinition[] {
  return (raw as RawCard[])
    .map(({ _namedAbilityStubs: _, ...card }) => card as unknown as CardDefinition);
}

const cards = [
  ...loadSet(set001),
  // ...loadSet(set002),
];

export const LORCAST_CARD_DEFINITIONS: Record<string, CardDefinition> =
  Object.fromEntries(cards.map((c) => [c.id, c]));

export const LORCAST_CARDS: CardDefinition[] = cards;
